// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCabypYCPOKzsJfiQB59ikL1UryH4pMk8E',
    appId: '1:758012922922:web:a20f71afe3e73541dfc753',
    messagingSenderId: '758012922922',
    projectId: 'hasnan-fluttersemester4',
    authDomain: 'hasnan-fluttersemester4.firebaseapp.com',
    storageBucket: 'hasnan-fluttersemester4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGvXNbblfr6la2sjmHbzxl64QVy7y_cvE',
    appId: '1:758012922922:android:10724cb31196898edfc753',
    messagingSenderId: '758012922922',
    projectId: 'hasnan-fluttersemester4',
    storageBucket: 'hasnan-fluttersemester4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvXUsFER9AJAgdpoMPfyD5SpHYMWF-MkE',
    appId: '1:758012922922:ios:2fc5a65acb29f8c9dfc753',
    messagingSenderId: '758012922922',
    projectId: 'hasnan-fluttersemester4',
    storageBucket: 'hasnan-fluttersemester4.firebasestorage.app',
    iosBundleId: 'com.example.hasnanLatihan2pertemuan4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvXUsFER9AJAgdpoMPfyD5SpHYMWF-MkE',
    appId: '1:758012922922:ios:2fc5a65acb29f8c9dfc753',
    messagingSenderId: '758012922922',
    projectId: 'hasnan-fluttersemester4',
    storageBucket: 'hasnan-fluttersemester4.firebasestorage.app',
    iosBundleId: 'com.example.hasnanLatihan2pertemuan4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCabypYCPOKzsJfiQB59ikL1UryH4pMk8E',
    appId: '1:758012922922:web:8b8759c0cc687956dfc753',
    messagingSenderId: '758012922922',
    projectId: 'hasnan-fluttersemester4',
    authDomain: 'hasnan-fluttersemester4.firebaseapp.com',
    storageBucket: 'hasnan-fluttersemester4.firebasestorage.app',
  );
}
